---
- hosts: all
  vars:
    - container_image: fedora
    - container_command: bash
    - count: 1
  tasks:
  - command: "docker run -itd --name container{{ item }} {{ container_image }} {{ container_command }}"
    with_sequence: count={{ count }}

