---
- hosts: all
  vars:
    - container_image: fedora
    - container_command: bash
    - count: 1
  ignore_errors: True
  tasks:
  - command: "docker run -itd --name container{{ item }} {{ container_image }} {{ container_command }}"
    with_sequence: count={{ count }}
    
  - command: "docker images -q {{ container_image }}"
    register: output
    
  - set_stats:
      data:
        container_group: "image_{{ output.stdout }}"

