---
- hosts: all
  vars:
    - container_name: awesome_ansible
    - container_image: fedora
    - container_command: bash
  tasks:
  - command: "docker run -itd --name {{ container_name }} {{ container_image }} {{ container_command }}"

