---
- name: Create a Docker container
  hosts: all
  vars:
    - container_name: awesome_ansible
  tasks:
  - name: Create a container
    docker_container:
      name: "{{ container_name }}"
      image: fedora
      command: bash
      state: present
      detach: yes
      tty: yes
      interactive: yes
