---
- hosts: "{{ target }}"  #all
  vars:
    - container_image: fedora
    - container_command: bash
    - count: 1
  ignore_errors: True
  tasks:
  - command: "docker run -itd --name container{{ item }} {{ container_image }} {{ container_command }}"
    with_sequence: count={{ count }}
    
  - set_stats:
      data:
        container_group: "image_{{ container_image }}"

