---
- name: Create a Docker container
  hosts: all
  tasks:
  - name: Create a Docker container
    docker_container:
      name: awesome_ansible
      image: fedora
      command: bash
      state: present
      detach: yes
      tty: yes
      interactive: yes
