---
- name: Create a Docker container
  hosts: all
  vars:
    - count: 1
  tasks:
  - name: Create a Docker container
    docker_container:
      name: "container{{ item }}"
      image: fedora
      state: absent
    with_sequence: count={{ count }}
