---
- hosts: all
  become: True
  become_method: su
  gather_facts: False
  tasks:
  - name: Configure motd file
    copy:
      content: "Container {{inventory_hostname}} is managed by Ansible."
      dest: /etc/motd
    when: inventory_hostname in groups[ container_group ][0]
